spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/new_db
    username: postgres
    password: 1221
    driver-class-name: org.postgresql.Driver
    dbcp2:
      default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    default-schema: public